name: Weekly PR Analysis

on:
  # Run every Monday at 9 AM UTC
  schedule:
    - cron: '0 9 * * 1'

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to analyze (owner/repo)'
        required: false
        default: 'github/copilot-sdk'

jobs:
  analyze-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Install Copilot CLI
        run: |
          gh extension install github/gh-copilot || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run PR analysis
        run: |
          REPO="${{ github.event.inputs.repository || 'github/copilot-sdk' }}"
          npm start -- --repo "$REPO" --non-interactive --output ./output
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        with:
          name: pr-analysis-report-${{ github.run_number }}
          path: output/
          retention-days: 30

      - name: Comment on issue (optional)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Analysis complete! Check the artifacts for detailed reports."
          # You can extend this to post results to an issue or PR